# Site settings
title: RotaSambadh
subtitle: "A Navigator to your Destination"
url: "https://rotasambandh.com" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
timezone: Asia/Kolkata

# icon: /assets/images/logo3.png

description: RotaSambandh connects you with the Achievers and Established professionals ie.Mentors(Rotarians) from various classifications of your Choice and Passion. This Project is initiated by Rotaract Bangalore East under the leadership of Rtr. Rtr. Arun Teja Godavarthi (aka. ZeoSpec).

# Build settings
markdown: kramdown
# highlighter: rouge
# permalink: blog/:year/:month/:day/:title/
# paginate: 4
# paginate_path: blog/page-:num/

# Google analytics
# ga_tracking_id: "UA-122171689-6"
# ga_tag_manage_id: "GTM-TTR59PS"

plugins:
  - jekyll-sitemap
  
collections:
  classifications:
    output: true
    permalink: /classifications/:path/

include:
  - _redirects