# Site settings
title: RotaSambandh
subtitle: "A Navigator to your Destination"
url: "https://rotasambandh.com"
baseurl: ""
timezone: Asia/Kolkata

description: RotaSambandh connects Rotaractors with the Achievers and Established professionals ie.Mentors-Rotarians from various classifications on the Choice and Passion of Rotaractor. RotaSambandh consists of two formats CONNECT WITH MENTOR and SHADOW THE MENTOR. RotaSambandh is a project created by Rtr. Rtn. Arun Teja Godavarthi aka. ZeoSpec of Rotaract Bangalore East.

# Build settings
markdown: kramdown
highlighter: rouge
# permalink: blog/:year/:month/:day/:title/
# paginate: 4
# paginate_path: blog/page-:num/

plugins:
  - jekyll-sitemap
  
collections:
  classifications:
    output: true
    permalink: /classifications/:path/

include:
  - _redirects