# Site settings
title: RotaSambandh
subtitle: "A Navigator to your Destination"
url: "https://rotasambandh.com"
baseurl: ""
timezone: Asia/Kolkata

description: RotaSambandh connects you with the Achievers and Established professionals ie.Mentors(Rotarians) from various classifications of your Choice and Passion. This Project is initiated by Rotaract Bangalore East under the leadership of Rtr. Rtn. Arun Teja Godavarthi (aka. ZeoSpec).

# Build settings
markdown: kramdown
highlighter: rouge
# permalink: blog/:year/:month/:day/:title/
# paginate: 4
# paginate_path: blog/page-:num/

plugins:
  - jekyll-sitemap
  
collections:
  classifications:
    output: true
    permalink: /classifications/:path/

include:
  - _redirects